replicaCount: 1

image:
  repository: demo-app
  tag: v1
  pullPolicy: Never

appConfig:
  APP_ENV: dev
  LOG_LEVEL: debug

service:
  type: NodePort
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "250m"
    memory: "128Mi"
