pipeline {
    agent any

    environment {
        IMAGE_NAME = 'demo-app'
        IMAGE_TAG = 'jenkins-v1'
    }

    stages {
        stage('Show Workspace') {
            steps {
                sh '''
                pwd
                ls -la
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ./app
                docker images | grep ${IMAGE_NAME}
                '''
            }
        }
    }
}
