pipeline {
    agent any

    stages {
        stage('Show Workspace') {
            steps {
                sh '''
                echo "Current workspace:"
                pwd

                echo "Files:"
                ls -la

                echo "Project folders:"
                find . -maxdepth 2 -type d | sort
                '''
            }
        }

        stage('Basic Validation') {
            steps {
                sh '''
                test -d app
                test -d helm
                test -d terraform
                echo "Required folders exist."
                '''
            }
        }
    }
}
